# -*- coding: utf-8 -*-
"""AIFirstLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2qUKj6EDBBeWEYgH1OgwUGyW4b2aiJM

# HELLO
# Title

*   ADD
*   Subtract
*   Multiplication
*   Division
# New Section
"""

print("hello");
a = 6;
b = 4;
addition = a + b;
subtract = a - b;
multiply = a * b;
division = a / b;
print("Addition:",addition);
print("Subtract:",subtract);
print("Multiplication:",multiply);
print("Division:",division);