# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-qQ6X9rGIHwVh-YFGvehwZin__nixpY
"""

# create  a list of 10 integer
a = [10,12,13,14,15,11,16,17,18,19]
print("original list: " , a)
# find and print the sum,max,and min value
print("sum of the list: " , sum(a))
print("max value of the list: " , max(a))
print("min value of the list: " , min(a))
# add new element in the list
a.append(20)
print("new list: " , a)
# remove existing element from the list
a.remove(10)
print("new list: " , a)
# print new list
print("new list: " , a)
# sort the list in ascending order
a.sort()
print("new list: " , a)
# sort the list in descending order
a.sort(reverse=True)
print("new list: " , a)

"""# **Lists**
1. create  a list of 10 integers
2. find and print the sum,max,and min value
3. add new element to the list and remove an existing one
4. print new list
5. sort the list in ascending/descending order





"""

#create a tuple with 5 strings
a = ("apple", "banana", "cherry", "date", "elderberry")
print(a)
# access and print the second and last element
print(a[1])
print(a[-1])
# add new element to the tuple
b = list(a)
b.append("fig")
a = tuple(b)
print(a)
# remove an element from the tuple
b = list(a)
b.remove("apple")
a = tuple(b)
print(a)

"""# **Tuples**
1. create a tuple with 5 strings
2. access and print the second and last element
3. add new element to the tuple
4. remove an element from the tuple
"""

# create two sets with some common and unique elements
a = {1, 2, 3, 4, 5}
b = {4, 5, 6, 7, 8}
# find and print the union of the sets
print(a.union(b))
# find and print the intersection of the sets
print(a.intersection(b))
# find and print the difference between the sets
print(a.difference(b))
# find and print the symmetric difference between the sets
print(a.symmetric_difference(b))

"""# **Sets**
1. create two sets with some common and unique elements
2. find and print the union of the sets
3. find and print the intersection of the sets
4. find and print the difference between the sets
5. find and print the symmetric difference between the sets
"""

# create 5-key values pairs and marks
students = {"Ali" : 85,"Sara" : 92,"Ahmed" : 78,"Fatima" : 95,"Hassan" : 88}
print(students)
# find and print the length of the dictionary
print(len(students))
# find and print the keys of the dictionary
print(students.keys())
# find and print the values of the dictionary
print(students.values())
# update value
students ["Ali"] = 90;
print("update dictionary: ", students)

"""# **Dictionaries**
1. 5 key value pairs student name and marks
2. print keys and values
3. update value

# **Numpy**

# **Matplotlib**
"""