# -*- coding: utf-8 -*-
"""LabWork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rk8NwT5Pxi0kCj3CbWOEL4KoQoqNxlHj
"""

# Create a dictionary to store student information
student = {
    "name": "Alisha",
    "age": 21,
    "roll_number": "BSSE123",
    "grade": "A"
}

# 1. Print all keys and values
print("All Keys:", student.keys())
print("All Values:", student.values())

# 2. Update the grade of the student
student["grade"] = "A+"

# 3. Add a new key 'email' with a value
student["email"] = "alisha@example.com"

# 4. Delete the 'roll_number' key
del student["roll_number"]

# Print final dictionary
print("\nUpdated Student Information:")
print(student)

# 1. Import the Matplotlib library
import matplotlib.pyplot as plt

# 2. Create a simple line plot
X = [1, 2, 3, 4, 5]
Y = [2, 4, 6, 8, 10]   # Example data (you can choose any values)

plt.plot(X, Y, marker='o', color='blue')
plt.title("Simple Line Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.grid(True)
plt.show()