# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwaY64WtjMI_GB2AsBaQBPpy3Vi0xsED
"""

# install numpy
! pip install numpy

import numpy as np

# Create 1D array
arr = np.arange(10, 31)
print('1D Array:', arr)

# Reshape to 3x7 matrix
matrix = arr.reshape(3, 7)
print('3x7 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(20, 49)
arr2_trimmed = arr2[:21]  # Trim arr2 to match arr's length
print('Addition:', arr + arr2_trimmed)
print('Multiplication:', arr * arr2_trimmed)

"""# **Numpy**
1. Import NumPy and create a 1D array of numbers from 10 to 30.
2. Reshape it into a 3x7 matrix.
3. Find the mean, median, and standard deviation of the array.
4. Create another array from 20 to 48 and trim it to match the length of the first array.
5. Perform element-wise addition and multiplication between the two arrays.
"""

# install matplotlib
!pip install matplotlib

import matplotlib.pyplot as plt

# Line Plot: Car speeds over time
time = list(range(1, 11))  # Time in seconds
speeds = [0, 15, 30, 45, 60, 70, 75, 80, 85, 90]  # Speed in mph
plt.plot(time, speeds)
plt.title('Time vs Car Speed')
plt.xlabel('Time (seconds)')
plt.ylabel('Speed (mph)')
plt.show()

# Bar Chart: Car brands and their sales numbers
car_brands = ['Toyota', 'Ford', 'BMW', 'Honda', 'Tesla']
sales = [1200, 950, 600, 850, 400]  # Number of cars sold
plt.bar(car_brands, sales, color='skyblue')
plt.title('Car Sales by Brand')
plt.xlabel('Car Brands')
plt.ylabel('Number of Cars Sold')
plt.show()

# Pie Chart: Market share of different car types
car_types = ['Sedan', 'SUV', 'Truck', 'Electric']
market_share = [40, 35, 15, 10]  # Percentage market share
plt.pie(market_share, labels=car_types, autopct='%1.1f%%', startangle=140)
plt.title('Market Share by Car Type')
plt.show()

"""# **Matplotlib**
1. Use Matplotlib to create the following plots:
* A line plot showing car speeds over time (in seconds).
* A bar chart showing sales numbers for 5 car brands.
* A pie chart showing the market share distribution of different car types.
2. Label the axes and add titles to each plot.
"""